### ISSUE TITLE
an error occurred

### ISSUE THREAD

**Issue by shen-lan** [SunsetMkt/Sunsetwarden#1]
Hello, an error occurred after installing the extension plugin. 
The file is dist-chrome-mv3-beta.zip  
chrome version:  130.0.6723.117。
------------------------------
Besides, could you please upload this plugin to the Google Chrome Web Store? It's really troublesome that I have to manually unzip and import it for installation every time there is an update

![image](https://github.com/user-attachments/assets/32a17938-2bf1-456e-96dc-9638810c52b7)

**Comment by SunsetMkt** [comment]
Do NOT use the BETA version. Try `dist-chrome-mv3.zip`.

I don't want to pay the ＄5 registration fee and doubt if this extension will pass Google's reviews.

**Comment by SunsetMkt** [comment]
Try this: https://chromewebstore.google.com/detail/sunsetwarden/leedpmmbobncoipdjocgcbkmogekjkga
